FROM python:3.8

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1

# Turns off buffering for easier logging
ENV PYTHONUNBUFFERED 1

WORKDIR ${APP_PATH}

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY app.py .

CMD ["python3", "app.py"]