version: "3"

services:

  zookeeper:
    image: ubuntu/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
      
  kafka:
    image: ubuntu/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: kafka:9092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  kafka-tweet-consumer:
    build: 
      context: ./kafka_tweet_consumer
    image: kafka-tweet-consumer:latest
    container_name: kafka-tweet-consumer
    depends_on:
      - kafka

  kafka-tweet-producer:
    build:
      context: ./kafka_tweet_producer/
    image: kafka-tweet-producer:latest
    volumes:
      - ./data:/app/data
    container_name: kafka-tweet-producer
    depends_on:
      - kafka-tweet-consumer