version: "3"

services:

  zookeeper:
    image: ubuntu/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
      
  kafka:
    image: ubuntu/kafka
    container_name: kafka
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_LISTENERS: ${KAFKA_ADVERTISED_HOST_NAME}:${KAFKA_PORT}
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  kafka-tweet-consumer:
    build: 
      context: ./kafka_tweet_consumer
    image: kafka-tweet-consumer:latest
    container_name: kafka-tweet-consumer
    environment:
      - KAFKA_ADVERTISED_HOST_NAME
      - KAFKA_PORT
      - KAFKA_API_VERSION
      - KAFKA_TOPIC_TRUMP
      - KAFKA_TOPIC_BIDEN
    depends_on:
      - kafka

  kafka-tweet-producer:
    build:
      context: ./kafka_tweet_producer/
    image: kafka-tweet-producer:latest
    container_name: kafka-tweet-producer
    volumes:
      - ./data:${DATA_PATH}
    environment:
      - KAFKA_ADVERTISED_HOST_NAME
      - KAFKA_PORT
      - KAFKA_API_VERSION
      - KAFKA_TOPIC_TRUMP
      - KAFKA_TOPIC_BIDEN
      - FILE_PATH_TRUMP
      - FILE_PATH_BIDEN
    depends_on:
      - kafka-tweet-consumer