version: "3"

services:

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
      
  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:${KAFKA_PORT}
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}

  kafka-producer:
    build: ./kafka
    image: kafka-producer:0.1
    container_name: kafka-producer
    depends_on:
      - kafka
      - spark-submit
    environment:
      - KAFKA_ADVERTISED_HOST_NAME
      - KAFKA_PORT
      - KAFKA_API_VERSION
      - KAFKA_TOPIC_TRUMP
      - KAFKA_TOPIC_BIDEN
      - FILE_PATH_TRUMP
      - FILE_PATH_BIDEN
    volumes:
      - ./data:${DATA_PATH}

  spark-master:
    image: bitnami/spark:3.3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '7077:7077'

  spark-worker:
    image: bitnami/spark:3.3.2
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - '8081:8081'

  spark-submit:
    build: ./spark
    image: spark-submit:0.1
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker
      - kafka
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - KAFKA_ADVERTISED_HOST_NAME
      - KAFKA_PORT
      - KAFKA_API_VERSION
      - KAFKA_TOPIC_TRUMP
      - KAFKA_TOPIC_BIDEN